Repository xenanetworks/open-automation-utilities, pull requests merged in 2023-02, with the labels that each got.

#4 docs: Update installation
  docs/source/getting_started/installation.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/introduction.rst
Labels: documentation

#29 improve(log): Save log display horizontal space
  xoa_utils/__init__.py
  xoa_utils/clicks/click_commands/anlt.py
Labels: improvement

#26 Added support for the link-train algorithm select
  xoa_utils/clicks/click_commands/anlt.py
  xoa_utils/clicks/click_commands/lt.py
  xoa_utils/clis/__init__.py
  xoa_utils/clis/cli_utils.py
  xoa_utils/cmds/cmd_context.py
Labels: feature

#34 Change lt preset args and improve docstrings
  xoa_utils/clicks/click_commands/an.py
  xoa_utils/clicks/click_commands/anlt.py
  xoa_utils/clicks/click_commands/debug.py
  xoa_utils/clicks/click_commands/lt.py
  xoa_utils/clicks/click_commands/management.py
Labels: documentation, improvement
